# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './info_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Models.Class.Command_management import Command_manager

class Ui_Dialog_Client(object):
    def __init__(self,data):
        for row in data:
            row.pop(0)
            row.pop(5)
            row.pop(5)
            print(row)
            self.data = row

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(509, 495)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 531, 511))
        self.widget.setStyleSheet("background-color: rgb(255,228,54)")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(190, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff;\n"
"background: transparent;")
        self.label.setObjectName("label")
        self.nom_field = QtWidgets.QLineEdit(self.widget)
        self.nom_field.setGeometry(QtCore.QRect(130, 120, 251, 41))
        self.nom_field.setStyleSheet("border-radius:5px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.nom_field.setObjectName("nom_field")
        self.valider = QtWidgets.QPushButton(self.widget)
        self.valider.setGeometry(QtCore.QRect(150, 410, 211, 32))
        font = QtGui.QFont()
        font.setFamily("metropolis")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.valider.setFont(font)
        self.valider.setStyleSheet("QPushButton{\n"
"background-color:rgba(0,0,0,0.2);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font:77 15pt \"metropolis\";\n"
"border-radius:5px;\n"
"font-weight:bold;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-radius:5px;\n"
"color:rgb(0,0,0);\n"
"font:77 15pt \"metropolis\";\n"
"\n"
"font-weight:bold;\n"
"}\n"
"")
        self.valider.setObjectName("valider")
        self.prenom_field = QtWidgets.QLineEdit(Dialog)
        self.prenom_field.setGeometry(QtCore.QRect(120, 170, 251, 41))
        self.prenom_field.setStyleSheet("border-radius:5px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.prenom_field.setObjectName("prenom_field")
        self.telephone_field = QtWidgets.QLineEdit(Dialog)
        self.telephone_field.setGeometry(QtCore.QRect(120, 230, 251, 41))
        self.telephone_field.setStyleSheet("border-radius:5px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.telephone_field.setObjectName("telephone_field")
        self.quartier_field = QtWidgets.QLineEdit(Dialog)
        self.quartier_field.setGeometry(QtCore.QRect(120, 290, 251, 41))
        self.quartier_field.setStyleSheet("border-radius:5px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.quartier_field.setObjectName("quartier_field")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Info Client"))
        self.nom_field.setPlaceholderText(_translate("Dialog", "  Nom"))
        self.valider.setText(_translate("Dialog", "Valider"))
        self.valider.clicked.connect(lambda : Command_manager.create_command(self,[self.data,[self.nom_field.text(),self.prenom_field.text(),self.telephone_field.text(), self.quartier_field.text()]]))
        self.prenom_field.setPlaceholderText(_translate("Dialog", "  Prenom"))
        self.telephone_field.setPlaceholderText(_translate("Dialog", "Telephone"))
        self.quartier_field.setPlaceholderText(_translate("Dialog", "  Quartier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_Client()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
