# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Vue/Design/Dialogue_edite_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Models.Class.User_management import User_manager

class Ui_Dialog(User_manager):
    def __init__(self, data):
        self.data = data
        print("Writing: {}".format(data))

        print("Size: {}".format(len(self.data)))

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(612, 496)
        Dialog.setStyleSheet("background-color: #FFE436;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: #FFE436;")
        self.widget.setObjectName("widget")
        self.username_fielde = QtWidgets.QLineEdit(self.widget)
        self.username_fielde.setGeometry(QtCore.QRect(120, 170, 361, 41))
        self.username_fielde.setStyleSheet("border-radius:8px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.username_fielde.setObjectName("username_fielde")
        self.email_fielde = QtWidgets.QLineEdit(self.widget)
        self.email_fielde.setGeometry(QtCore.QRect(120, 230, 361, 41))
        self.email_fielde.setStyleSheet("border-radius:8px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.email_fielde.setObjectName("email_fielde")
        self.btn_update = QtWidgets.QPushButton(self.widget)
        self.btn_update.setGeometry(QtCore.QRect(190, 420, 181, 32))
        self.btn_update.setStyleSheet("QPushButton{\n"
"background-color:#fff;\n"
"border-top-left-radius:8px;\n"
"border-bottom-left-radius:8px;\n"
"color:#000;\n"
"font:77 21pt \"metropolis\";\n"
"border-radius:8px;\n"
"}\n"
"\n"
"")
        self.btn_update.setObjectName("btn_update")
        self.name_fielde = QtWidgets.QLineEdit(self.widget)
        self.name_fielde.setGeometry(QtCore.QRect(310, 110, 171, 41))
        self.name_fielde.setStyleSheet("border-radius:8px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.name_fielde.setObjectName("name_fielde")
        self.profile_combo = QtWidgets.QComboBox(self.widget)
        self.profile_combo.setGeometry(QtCore.QRect(120, 350, 361, 41))
        if self.data[6] == 'Admin':
            self.profile_combo.addItem('Admin')
            self.profile_combo.addItem('Caissier')
        else:
            self.profile_combo.addItem('Caissier')
            self.profile_combo.addItem('Admin')
        self.profile_combo.setStyleSheet("border-radius:8px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.profile_combo.setObjectName("profile_combo")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(140, 50, 341, 41))
        self.label_7.setStyleSheet("background-color:none;\n"
"border:none;\n"
"font:90 30pt \"metropolis\";\n"
"font-size:30px;\n"
"color:white")
        self.label_7.setObjectName("label_7")
        self.tel_fielde = QtWidgets.QLineEdit(self.widget)
        self.tel_fielde.setGeometry(QtCore.QRect(120, 290, 361, 41))
        self.tel_fielde.setStyleSheet("border-radius:8px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.tel_fielde.setObjectName("tel_fielde")
        self.prenom_filde = QtWidgets.QLineEdit(self.widget)
        self.prenom_filde.setGeometry(QtCore.QRect(120, 110, 171, 41))
        self.prenom_filde.setAutoFillBackground(False)
        self.prenom_filde.setStyleSheet("border-radius:8px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.prenom_filde.setObjectName("prenom_filde")
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.username_fielde.setPlaceholderText(_translate("Dialog", "Username"))
        self.email_fielde.setPlaceholderText(_translate("Dialog", "email"))
        self.btn_update.setText(_translate("Dialog", "Update"))
        self.name_fielde.setPlaceholderText(_translate("Dialog", "Nom"))
        self.profile_combo.setPlaceholderText(_translate("Dialog", "Profile"))
        self.label_7.setText(_translate("Dialog", "EDITER UN COMPTE"))
        self.tel_fielde.setPlaceholderText(_translate("Dialog", "téléphone"))
        self.prenom_filde.setPlaceholderText(_translate("Dialog", "Prenom"))

        self.name_fielde.setText(_translate("Dialog", self.data[1]))
        self.prenom_filde.setText(_translate("Dialog", self.data[2]))
        self.username_fielde.setText(_translate("Dialog", self.data[3]))
        self.email_fielde.setText(_translate("Dialog", self.data[4]))
        self.tel_fielde.setText(_translate("Dialog", self.data[5]))
        self.btn_update.clicked.connect(lambda: self.update_user({
            'nom': self.name_fielde.text(),
            'prenom': self.prenom_filde.text(),
            'username': self.username_fielde.text(),
            'email': self.email_fielde.text(),
            'tel': self.tel_fielde.text(),
            'profil': self.profile_combo.currentText(),
        }))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
