# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Vue/Design/EditeProductBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Models.Class import Product_management


class Ui_Dialog_Product(Product_management.Product_manager):
    def __init__(self,data):
        self.data = data
        print("Writing: {}".format(data))
        print("Size: {}".format(len(self.data)))

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 649)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 661, 651))
        self.frame.setStyleSheet("background-color: rgb(255,228,54)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(50, 70, 571, 501))
        self.frame_3.setStyleSheet("background-color:rgba(0,0,0,0.2);\n"
"border-radius:20px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.update = QtWidgets.QPushButton(self.frame_3)
        self.update.setGeometry(QtCore.QRect(190, 420, 181, 32))
        self.update.setStyleSheet("QPushButton{\n"
"background-color:#FFE436;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font:77 21pt \"metropolis\";\n"
"border-radius:15px\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-radius:15px;\n"
"color:rgb(0,0,0);\n"
"font:77 18pt \"metropolis\";\n"
"\n"
"\n"
"}\n"
"")
        self.update.setObjectName("update")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(120, 20, 371, 41))
        self.label_14.setStyleSheet("background-color:none;\n"
"border:none;\n"
"font:90 30pt \"metropolis\";\n"
"font-size:30px;\n"
"color:white")
        self.label_14.setObjectName("label_14")
        self.montant_field = QtWidgets.QLineEdit(self.frame_3)
        self.montant_field.setGeometry(QtCore.QRect(80, 280, 411, 41))
        self.montant_field.setStyleSheet("border-radius:15px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.montant_field.setObjectName("montant_field")
        self.quantiter_field = QtWidgets.QLineEdit(self.frame_3)
        self.quantiter_field.setGeometry(QtCore.QRect(290, 210, 201, 41))
        self.quantiter_field.setStyleSheet("border-radius:15px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.quantiter_field.setObjectName("quantiter_field")
        self.product_field = QtWidgets.QLineEdit(self.frame_3)
        self.product_field.setGeometry(QtCore.QRect(80, 80, 411, 41))
        self.product_field.setStyleSheet("border-radius:15px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.product_field.setObjectName("product_field")
        self.categorie_combo = QtWidgets.QComboBox(self.frame_3)
        self.categorie_combo.addItem(self.data[2])
        for category in self.selectFiew():
            self.categorie_combo.addItem(category)

        self.categorie_combo.setGeometry(QtCore.QRect(80, 140, 411, 41))
        self.categorie_combo.setStyleSheet("border-radius:15px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.categorie_combo.setObjectName("categorie_combo")
        self.prix_field = QtWidgets.QLineEdit(self.frame_3)
        self.prix_field.setGeometry(QtCore.QRect(80, 210, 201, 41))
        self.prix_field.setStyleSheet("border-radius:15px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.prix_field.setObjectName("prix_field")
        self.etat_combo = QtWidgets.QComboBox(self.frame_3)
        self.etat_combo.setGeometry(QtCore.QRect(80, 350, 411, 41))
        self.etat_combo.addItem('Disponible')
        self.etat_combo.addItem('Indisponible')
        self.etat_combo.setStyleSheet("border-radius:15px;\n"
"color:black;\n"
"background-color:rgba(255,255,255,0.8)\n"
"\n"
"")
        self.etat_combo.setObjectName("etat_combo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.update.setText(_translate("Dialog", "Modifier"))
        self.label_14.setText(_translate("Dialog", "EDITER UN PRODUIT"))
        self.montant_field.setPlaceholderText(_translate("Dialog", "Montant"))
        self.quantiter_field.setPlaceholderText(_translate("Dialog", "Quantité"))
        self.product_field.setPlaceholderText(_translate("Dialog", "Product"))
        self.categorie_combo.setPlaceholderText(_translate("Dialog", "categorie_produit"))
        self.prix_field.setPlaceholderText(_translate("Dialog", "prix_unitaire"))
        self.etat_combo.setPlaceholderText(_translate("Dialog", "etat"))

        self.product_field.setText(_translate("Dialog", self.data[1]))
        self.quantiter_field.setText(_translate("Dialog", self.data[3]))
        self.prix_field.setText(_translate("Dialog", self.data[4]))
        self.montant_field.setText(_translate("Dialog", self.data[6]))
        self.update.clicked.connect(lambda :self.update_product({
            'id': self.data[0],
            'nom_produit': self.product_field.text(),
            'categorie':self.categorie_combo.currentText(),
            'quantiter':self.quantiter_field.text(),
            'prix':self.prix_field.text(),
            'etat':self.etat_combo.currentText(),
            'montant':self.montant_field.text()
        }))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog_Product()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())