# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schoolProjectGestionBoutique.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5.QtWidgets import QMessageBox

sys.path.append('../Models')

from PyQt5 import QtCore, QtGui, QtWidgets

########################################################################
  ################### My personnal Import #############################
########################################################################
# from Models import Btn_methodes
from Models import LoginManager



class Ui_Form(LoginManager.LoginManager):


    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(546, 547)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, -20, 551, 651))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-20, 20, 571, 621))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(20, -5, 621, 631))
        self.label.setStyleSheet("border-image: url(:/Images/Images/log.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 491, 441))
        self.label_2.setStyleSheet("border-image: url(:/Images/Images/just.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(100, 90, 371, 361))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,0.2);\n"
"border-radius:25px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(250, 50, 61, 61))
        self.label_4.setMinimumSize(QtCore.QSize(2, 0))
        self.label_4.setStyleSheet("border-image: url(:/Images/Images/LG.png);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.connexion = QtWidgets.QPushButton(self.widget_2)
        self.connexion.setGeometry(QtCore.QRect(210, 420, 151, 61))
        self.connexion.setStyleSheet("background-color:rgba(255,255,255,0.9);\n"
"border-radius:30px;\n"
"box-shadow: 20px 20px 10px 10px black  ;\n"
"font-size:15px")
        self.connexion.setObjectName("connexion")
        self.username = QtWidgets.QLineEdit(self.widget_2)
        self.username.setGeometry(QtCore.QRect(140, 170, 301, 41))
        self.username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(255,255,255,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bootom:7px;")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.widget_2)
        self.password.setEnabled(True)
        self.password.setGeometry(QtCore.QRect(140, 260, 301, 41))
        self.password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(255,255,255,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bootom:7px;")
        self.password.setText("")
        self.password.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password.setObjectName("password")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(220, 350, 191, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.connexion.setText(_translate("Form", "Se connecter"))
        self.username.setPlaceholderText(_translate("Form", "  Username"))
        self.password.setPlaceholderText(_translate("Form", "  password"))
        self.label_5.setText(_translate("Form", "Mot de passe oublier ?"))


        self.connexion.clicked.connect(lambda :self.authication(self.username.text(), self.password.text))
        self.username.returnPressed.connect(lambda :self.authication(self.username.text(), self.password.text()))
        self.password.returnPressed.connect(lambda: self.authication(self.username.text(), self.password.text()))




import ressource
