# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
sys.path.append('../Models')

from PyQt5 import QtCore, QtGui, QtWidgets
from Models.LoginManager import LoginManager

class Ui_file1(LoginManager):

    def setupUi(self, file1):
        file1.setObjectName("file1")
        file1.resize(661, 714)
        self.widget = QtWidgets.QWidget(file1)
        self.widget.setGeometry(QtCore.QRect(0, -20, 551, 651))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(file1)
        self.widget_2.setGeometry(QtCore.QRect(-60, 0, 761, 721))
        self.widget_2.setObjectName("widget_2")
        self.label_back = QtWidgets.QLabel(self.widget_2)
        self.label_back.setGeometry(QtCore.QRect(50, -5, 681, 721))
        self.label_back.setStyleSheet("border-image: url(:/images/images/log.png);")
        self.label_back.setText("")
        self.label_back.setObjectName("label_back")
        self.label_imgpng = QtWidgets.QLabel(self.widget_2)
        self.label_imgpng.setGeometry(QtCore.QRect(20, -10, 531, 451))
        self.label_imgpng.setStyleSheet("border-image: url(:/images/images/IMG-20230104-WA0004_1-removebg-preview.png);")
        self.label_imgpng.setText("")
        self.label_imgpng.setObjectName("label_imgpng")
        self.label_morphose = QtWidgets.QLabel(self.widget_2)
        self.label_morphose.setGeometry(QtCore.QRect(230, 130, 371, 391))
        self.label_morphose.setStyleSheet("background-color:rgba(0,0,0,0.2);\n"
"border-radius:25px;")
        self.label_morphose.setText("")
        self.label_morphose.setObjectName("label_morphose")
        self.label_icon = QtWidgets.QLabel(self.widget_2)
        self.label_icon.setGeometry(QtCore.QRect(390, 90, 61, 61))
        self.label_icon.setStyleSheet("border-image: url(:/images/images/LG.png);\n"
"")
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")
        self.ButtonConnect = QtWidgets.QPushButton(self.widget_2)
        self.ButtonConnect.setGeometry(QtCore.QRect(340, 490, 151, 61))
        self.ButtonConnect.setStyleSheet("background-color:rgba(255,255,255,0.9);\n"
"border-radius:30px;\n"
"box-shadow: 20px 20px 10px 10px black  ;\n"
"font-size:15px\n"
"")
        self.ButtonConnect.setObjectName("ButtonConnect")
        self.input_Username = QtWidgets.QLineEdit(self.widget_2)
        self.input_Username.setGeometry(QtCore.QRect(270, 210, 301, 41))
        self.input_Username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(255,255,255,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bootom:7px;")
        self.input_Username.setObjectName("input_Username")
        self.input_password = QtWidgets.QLineEdit(self.widget_2)
        self.input_password.setGeometry(QtCore.QRect(270, 300, 301, 41))
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(255,255,255,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bootom:7px;")
        self.input_password.setObjectName("input_password")
        self.ButtonMdp = QtWidgets.QPushButton(self.widget_2)
        self.ButtonMdp.setGeometry(QtCore.QRect(330, 390, 191, 32))
        self.ButtonMdp.setStyleSheet("border:none;\n"
"background-color:none;")
        self.ButtonMdp.setObjectName("ButtonMdp")

        self.retranslateUi(file1)
        QtCore.QMetaObject.connectSlotsByName(file1)

    def retranslateUi(self, file1):
        _translate = QtCore.QCoreApplication.translate
        file1.setWindowTitle(_translate("file1", "Form"))
        self.ButtonConnect.setText(_translate("file1", "Se connecter"))
        self.input_Username.setPlaceholderText(_translate("file1", "  Username"))
        self.input_password.setPlaceholderText(_translate("file1", "  password"))
        self.ButtonMdp.setText(_translate("file1", "Mot de passe oublier ?"))

        self.ButtonConnect.clicked.connect(lambda: self.authication_conf(self.input_Username.text(), self.input_password.text()))

        self.input_Username.returnPressed.connect(lambda: self.authication_conf(self.input_Username.text(), self.input_password.text()))
        self.input_password.returnPressed.connect(lambda: self.authication_conf(self.input_Username.text(), self.input_password.text()))


    def closeWindow(self):
        self.widget.close()
        pass


import ressource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    file1 = QtWidgets.QWidget()
    ui = Ui_file1()
    ui.setupUi(file1)
    file1.exec_()
    sys.exit(app.exec_())
# password = Bamako2023@